// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-na5LcP9_dhiFe7B-oySxrwBZchtwEUI',
    appId: '1:1064396867130:web:4480f17441dc1c4bb79703',
    messagingSenderId: '1064396867130',
    projectId: 'portfolio-316fa',
    authDomain: 'portfolio-316fa.firebaseapp.com',
    storageBucket: 'portfolio-316fa.appspot.com',
    measurementId: 'G-YZ50990Q5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJGp07UEYcupG4ggrH5J724qawlDQwWac',
    appId: '1:1064396867130:android:da960b2173469f0cb79703',
    messagingSenderId: '1064396867130',
    projectId: 'portfolio-316fa',
    storageBucket: 'portfolio-316fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2AYIOzu7x_uIb26Y-lULKptNsE5ruhXE',
    appId: '1:1064396867130:ios:24565ff94f6d798cb79703',
    messagingSenderId: '1064396867130',
    projectId: 'portfolio-316fa',
    storageBucket: 'portfolio-316fa.appspot.com',
    iosBundleId: 'com.example.portfolio',
  );
}
